brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoListListView,
    TodoListDetailView,
    TodoListCreateView,
    TodoListUpdateView,
    TodoListDeleteView,
    TodoItemCreateView,
    TodoItemUpdateView,
)


urlpatterns = [
    path("", TodoListListView.as_view(), name="list_todos"),
    path("<int:pk>/", TodoListDetailView.as_view(), name="show_todolist"),
    path("create/", TodoListCreateView.as_view(), name="create_todolist"),
    path(
        "<int:pk>/edit/", TodoListUpdateView.as_view(), name="update_todolist"
    ),
    path(
        "<int:pk>/delete/", TodoListDeleteView.as_view(), name="delete_todolist"
    ),
    path("items/create/", TodoItemCreateView.as_view(), name="create_todoitem"),
    path(
        "items/<int:pk>/edit/",
        TodoItemUpdateView.as_view(),
        name="update_todoitem",
    ),
]

todos/models.py
from typing import Optional
from django.db import models


# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList", related_name="items", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.task

todos/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.urls import reverse_lazy
from todos.models import TodoItem, TodoList


# Create your views here.
# views for TodoList
class TodoListListView(ListView):
    model = TodoList
    template_name = "todos/list.html"


class TodoListDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"


class TodoListCreateView(CreateView):
    model = TodoList
    fields = ["name"]
    template_name = "todos/new.html"
    # success_url = reverse_lazy('show_todolist', )

    def get_success_url(self) -> str:
        return reverse_lazy("show_todolist", args=[self.object.id])


class TodoListUpdateView(UpdateView):
    model = TodoList
    fields = ["name"]
    template_name = "todos/edit.html"

    def get_success_url(self) -> str:
        return reverse_lazy("show_todolist", args=[self.object.id])


class TodoListDeleteView(DeleteView):
    model = TodoList
    template_name = "todos/delete.html"
    success_url = reverse_lazy("list_todos")


# views for TodoItem
class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "todos/item_new.html"
    fields = "__all__"

    def get_success_url(self) -> str:
        return reverse_lazy("show_todolist", args=[self.object.list.id])


class TodoItemUpdateView(UpdateView):
    model = TodoItem
    template_name = "todos/item_edit.html"
    fields = "__all__"

    def get_success_url(self) -> str:
        return reverse_lazy("show_todolist", args=[self.object.list.id])

todos/templates/todos/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>delete todo list</title>
</head>
<body>
    <main>
        <div>
            <h1>Are you sure?</h1>
            <form method="POST">
                {% csrf_token %}
                <button>Delete</button>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>todo list detail</title>
</head>
<body>
    <main>
        <div>
            <h1>{{todolist}}</h1>
            <p><a href="{% url 'update_todolist' todolist.id %}">Edit</a></p>
            <p><a href="{% url 'delete_todolist' todolist.id %}">Delete</a></p>
            <h2>Tasks</h2>
            <table>
                <thead>
                    <tr>
                        <td>Name</td>
                        <td>Due date</td>
                    </tr>
                </thead>
                <tbody>
                    {% for item in todolist.items.all %}
                        <tr>
                            <td><a href="{% url 'update_todoitem' item.id %}">{{item.task}}</a></td>
                            <td>{{item.due_date}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</body>
</html>

todos/templates/todos/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>edit todo list</title>
</head>
<body>
    <main>
        <div>
            <h1>Update list</h1>
            <form method="POST">
                {% csrf_token %}
                <input type="text" name="name">
                <button>Update</button>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/item_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>edit todo item</title>
</head>
<body>
    <main>
        <div>
            <h1>Update item</h1>
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button>Update</button>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/item_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>create new todo item</title>
</head>
<body>
    <main>
        <div>
            <h1>Create a new item</h1>
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button>Submit</button>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>todo list list</title>
</head>
<body>
    <main>
        <div>
            <h1>My Lists</h1>
            <p><a href="{% url 'create_todolist' %}">Create a new list</a></p>
            <p><a href="{% url 'create_todoitem' %}">Create a new item</a></p>
            <table>
                <thead>
                    <tr>
                        <td>Name</td>
                        <td>Number of items</td>
                    </tr>
                </thead>
                <tbody>
                    {% for list in todolist_list %}
                        <tr>
                            <td><a href="{% url 'show_todolist' list.id %}">{{list.name}}</a></td>
                            <td>{{list.items.all|length}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</body>
</html>

todos/templates/todos/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>create new todo list</title>
</head>
<body>
    <main>
        <div>
            <h1>Create a new list</h1>
            <form method="POST">
                {% csrf_token %}
                <input type="text" name="name">
                <button>Submit</button>
            </form>
        </div>
    </main>
</body>
</html>